### ISSUE TITLE
With VIM keybindings, escape should never clear the command.

### ISSUE THREAD

**Issue by gregwebs** [warpdotdev/Warp#3919]
### Describe the solution you'd like?

```Text
When using VIM keybindings, escape should never clear the command.
```

### Is your feature request related to a problem? Please describe.

```Text
I am unable to get used to checking the cursor for the VIM mode with Warp. Escape is my home base as a VIM user to get to the same known state. Except in Warp where I have to be on guard because it might instead clear the command I wanted to edit.

I just checked with Terminal- it operates the same way as Warp. However, Escape does not clear the command. I have used several different terminals over the years, always with vim keybindings, and escape has never cleared the command.

Warp keeps the state of the current VIM mode. Which is great when working continuously in the same terminal tab. However, once I switch between tabs, I don't remember what the mode was. This may be true of any context switch from the terminal to a different app, or stepping away from my computer, or just pausing to think about something else.
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by gregwebs** [comment]
Sorry, the flow is basically editing the last run command- what I do very frequently in a terminal.

Start with an empty prompt and press up one or more times. The highlighted command will show up in the terminal. Do not press Enter- that would execute the command. Instead, start editing the command.

If in normal mode, pressing escape will clear. If in insert mode, pressing escape once will move to normal mode (this is fine). Pressing again will clear.

<img width="507" alt="Screenshot 2023-12-01 at 8 52 26 AM" src="https://github.com/warpdotdev/Warp/assets/1183/e373746a-ab7f-4809-8115-3f11a70ba0cc">

**Comment by elviskahoro** [comment]
Oh got it! The issue was about editing history entries. This definitely needs a UX treatment

**Comment by hallettj** [comment]
As a newcomer Linux user I'll agree, this is quite frustrating.

A workaround for editing a previous command is to press up arrow to get to the command, and then press space or something - any change to the command dismisses the completions menu. Then it's safe to press escape. But my muscle memory keeps making me press escape immediately!

I would much rather have the behavior suggested here: pressing escape dismisses the completion menu, but does not clear the command. I think vim users will be more comfortable pressing `<esc>dd` if they want to clear the command. With vim keybindings escape should always be safe to press.

**Comment by ls-jacob-lawrence** [comment]
This issue has been my biggest problem with warp.
If I typo a command, then try to go back to it with history and quickly edit it with vim to add a different flag, change a word, whatever, the command is cleared instead. I shoot myself in the foot with this at least a few times a day.

I've been manually clicking into the command where I want the cursor to go instead, which is nasty.

Would love it if the behaviour was changed.

**Comment by skaven81** [comment]
I bump into this constantly when using Warp as well.  Would love to see it fixed.

**Comment by dannyneira** [comment]
Hi Folks, This issue has been resolved in the latest version of Warp. Closing as resolved, but please update and let us know if any issues.

**Comment by adamberenzweig** [comment]
Has this actually been fixed? I just installed warp (v0.2025.12.03.08.12.stable_05) and, with bash in vi mode (`set -o vi`), when I press escape it does not go into normal ("command") mode.  And the behavior that @gregwebs originally described is still present -- if you use the up-arrow to go back in history, and then hit escape, it clears the command.
