### ISSUE TITLE
Ctrl+Space always splits current pane

### ISSUE THREAD

**Issue by VandanRogheliya** [warpdotdev/Warp#5149]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I have a neovim setup with certain key bindings. One of them is <C-space> (Ctrl + Space).

Issue is that there seems to be a default key binding in Warp where this always splits the pane.

I am checked shortcuts settings, this key binding is not set.

### To reproduce

1. Open warp
2. Press Ctrl + Space
3. Pane splits

### Expected behavior

Pane should not split for Ctrl + Space if it is not set in the shortcut's setting.

### Screenshots

https://github.com/user-attachments/assets/3efd62d0-071a-45bd-b1c8-ccf26f743395

### Operating system

MacOS

### Operating system and version

14.5

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.07.16.08.02.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by maheshrijal** [comment]
I'm facing this issue on linux as well. `v0.2024.07.16.08.02.stable_03`

**Comment by wAuner** [comment]
I have the exact same problem. `ctrl-space` is not set anywhere and yet it opens a pane to the right (the same as cmd-d). No way to disable it, that's annoying.

**Comment by dannyneira** [comment]
Hey folks, sorry to hear about this. I don't suspect this is related to your neovim shortcuts. Unfortunately, I can't reproduce this on my end, so I also recommend you please check your settings for pane splits an set them to defaults instead of empty if possible to see if that helps.

Another suggestion which will reset all your Warp settings so they will be lost, but this may help with the issue I recommend is delete the user default settings with `defaults delete dev.warp.Warp-Stable` on Mac and `rm -r ${XDG_CONFIG_HOME:-$HOME/.config}/warp-terminal` on Linux.

**Comment by maheshrijal** [comment]
I just reset my settings (on linux) and this behavior is still there. Version: `v0.2024.07.23.08.02.stable_01`

**Comment by devdesai306** [comment]
I am facing this issue on Mac. Please fix this ASAP!

**Comment by Cesar-Carrio** [comment]
I have this same issue when using LunarVim.

**Comment by uesteibar** [comment]
I have the same issue here with nvim 😢

**Comment by Jean-Dv** [comment]
I have this same issue on `v0.2024.08.13.08.02.stable_04`

**Comment by Jean-Dv** [comment]
The error can fix with the next steps:
- Enter to shortcuts
- Search `New Agent Mode Pane`
- Clear shortcut

With this steps you can fix this error

**Comment by abulka** [comment]
> The error can fix with the next steps:
> 
> * Enter to shortcuts
> * Search `New Agent Mode Pane`
> * Clear shortcut
> 
> With this steps you can fix this error

This works yes, but ^ SPACE still doesn't get through to my shell. I usually have this key combination invoke a tool [tbmk](https://github.com/linhx/tbmk) which works in Mac terminal, but not in Warp.

**Comment by Serkan80** [comment]
Split pane down: ctrl +shift + e, also doesn't work on Linux (PopOS).

And when I right click and select "split pane down", then it works. But when I press "ctrl +shift + w" to close the new tab, then it also doesn't work.

**Comment by LeonardoTrapani** [comment]
Even if I change the shortcut of `New Agent Mode Pane`, the new shortcut works, but control + space still opens that.

**Comment by WiseyAI** [comment]
same issue on mac please fix

**Comment by MaraniMatias** [comment]
I am using vim, this issue is a big problem for me

**Comment by szgupta** [comment]
Hey y'all, sorry about the regression here. We'll have this fixed by the upcoming 01/30/24 release -- I'll follow up here once that fix is released.

**Comment by amin-bf** [comment]
Hey. Same Issue here. Any updates?

> Hey y'all, sorry about the regression here. We'll have this fixed by the upcoming 01/30/24 release -- I'll follow up here once that fix is released.

Do you mean 2025?

**Comment by szgupta** [comment]
Hey folks, update here: this is actually related to a more general issue with keybindings and we plan to have an update out in the next hour. Please follow along here: https://github.com/warpdotdev/Warp/issues/5741.

Again, sorry for the inconvenience this has caused.

**Comment by szgupta** [comment]
Update: the latest Warp version includes a patch for this! Sorry for the disruption y'all

**Comment by mrap** [comment]
Hmm, still seeing this on the latest version: `v0.2025.02.05.08.02.stable_03`

**Comment by szgupta** [comment]
Hey @mrap, can you provide a screen-recording of the behaviour you're seeing? `ctrl-space` shouldn't split into a new Agent Mode pane if the keybinding is clearer as described [here](https://github.com/warpdotdev/Warp/issues/5149#issuecomment-2303041214).

**Comment by IMKneat** [comment]
Clearing the shortcut for ctrl+space works for not opening the new agent mode pane, but the keybinding on neovim is still blocked

**Comment by kar0v** [comment]
Fresh new install on MacOS, Ctrl + space opens a new tab. No option to disable this.

**Comment by austindd** [comment]
For everyone running MacOS:

If you removed the Ctrl+Space key binding in Warp and are still having issues, make sure to ALSO disable the system keybinding for that as well.

Settings -> Keyboard -> Keyboard Shortcuts... -> Input Sources -> Select Previous Input Source

Just uncheck the setting or rebind it to another shortcut. This worked for me.

**Comment by samholmes** [comment]
I'm experience this issue. Why is this not fixed immediately? This is a really bad bug.

**Comment by lotharthesavior** [comment]
+1
