### ISSUE TITLE
Warp will not start unless run with sudo / sudo required

### ISSUE THREAD

**Issue by BrandonLeeDotDev** [warpdotdev/Warp#5179]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I cannot start warp w/o running as sudo

### To reproduce

No idea... 

Was not an issue before today.

### Expected behavior

Run as any user

### Operating system

Linux

### Operating system and version

Ubuntu 24.04

### Shell Version

zsh 5.9 (x86_64-ubuntu-linux-gnu)

### Current Warp version

cant access, reinstalled and cant log in

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by BrandonLeeDotDev** [comment]
![image](https://github.com/user-attachments/assets/be0946af-4fc1-4e5b-be55-2928a1337a09)

**Comment by BrandonLeeDotDev** [comment]
I assume the browser error is due to the fact that you cant run a browser as sudo?

**Comment by BrandonLeeDotDev** [comment]
It has magically started working...

**Comment by acarl005** [comment]
> It has magically started working...

Well that's strange! I'm going to close the issue since things are working now, but please re-open if the issue pops up again.

**Comment by eliorc** [comment]
I just ran to this as well. Also Ubuntu 24.04. Earlier today I updated Warp, not sure if it connected but I can't open it right now

This is the errors:
```
15:34:08 [INFO] Spawning terminal server process...
15:34:08 [INFO] Running terminal server...
15:34:08 [INFO] Running app with windowing system: X11
thread 'main' panicked at app/src/server/server_api/client.rs:9:10:
Reqwest Client must be able to be constructed: reqwest::Error { kind: Builder, source: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by BrandonLeeDotDev** [comment]
This is still happening to me as well

**Comment by eliorc** [comment]
BTW, running in another terminal `sudo warp-terminal` works. But it is not connected to my profile or any of my preferences

**Comment by mullerch** [comment]
https://github.com/seanmonstar/reqwest/issues/2391

**Comment by mullerch** [comment]
Workaround:

`env SSL_CERT_FILE="/etc/ssl/certs/ISRG_Root_X1.pem" warp-terminal`

Will work only if your have `/etc/ssl/certs/ISRG_Root_X1.pem` file and until the contacted API uses Let's Encrypt (or a certificate originated by ISRG Root X1)

**Comment by alokedesai** [comment]
Hi all, thanks for your patience here. I just merged a PR that fixes this issue by depending on an older version of  `rustls-native-certs` (@mullerch is correct that this is related to https://github.com/seanmonstar/reqwest/issues/2391).

**Comment by alokedesai** [comment]
For anyone experiencing this issue, could you download this build https://releases.warp.dev/stable/v0.2024.08.13.08.02.stable_04/warp-terminal_0.2024.08.13.08.02.stable.04_amd64.deb and see if it fixes your issue?

If so, the Warp team will prioritizing getting this released to all Linux users ASAP>

**Comment by eliorc** [comment]
> For anyone experiencing this issue, could you download this build https://releases.warp.dev/stable/v0.2024.08.13.08.02.stable_04/warp-terminal_0.2024.08.13.08.02.stable.04_amd64.deb and see if it fixes your issue?
> 
> If so, the Warp team will prioritizing getting this released to all Linux users ASAP>

@alokedesai can confirm that this build fix it for me

**Comment by mullerch** [comment]
@alokedesai Everything shows that https://github.com/seanmonstar/reqwest/issues/2391 and the underlying https://github.com/rustls/rustls-native-certs/issues/124 is the issue.

The 0.2024.08.13.08.02.stable.04 build fixes the issue for me.

**Comment by eliorc** [comment]
I'm avoiding clicking the "Update Warp" button, so it won't revert to the stable version where the bug still exists.
How will I know when is it safe to update Warp?

**Comment by DXrdjulmatov** [comment]
> For anyone experiencing this issue, could you download this build https://releases.warp.dev/stable/v0.2024.08.13.08.02.stable_04/warp-terminal_0.2024.08.13.08.02.stable.04_amd64.deb and see if it fixes your issue?
> 
> If so, the Warp team will prioritizing getting this released to all Linux users ASAP>

thanks, warp works as before

**Comment by alokedesai** [comment]
Hi everyone, the latest version of Warp is now available. You should see the "update available" check go away in the next few minutes if you're using the download link I sent yesterday.

Thanks again for your patience here, going to go ahead and close this out but please reopen if you're still experiencing issues.

**Comment by eliorc** [comment]
@alokedesai I'm not seeing any update, I'm on `v0.2024.08.13.08.02.stable_04`. 
Is there a command I should execute?

**Comment by alokedesai** [comment]
The fact that there's no update is correct :) We rolled out `v0.2024.08.13.08.02.stable_04` (the version with the fix) to all Linux users. If you downloaded the version via the link above (before it was fully rolled out to everyone), then there should be no additional action needed.
