### ISSUE TITLE
I can't copy UUIDs from command output. When I paste they show as asterisks.

### ISSUE THREAD

**Issue by swpalmer-cl** [warpdotdev/Warp#5581]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Copying command output that includes UUIDs doesn't work.  The pasted text has the UUIDs replaced with asterisks
E.g. I copy this:
```
2024-12-16 06:58:48   74020152 ab9865cf-fbf1-4e47-bc78-3e69418d3c6b
2024-12-16 07:00:20  204857981 525ba40e-3df4-4e64-8a33-098dcfba6680
2024-12-16 07:02:14  201311016 36b3b11e-e366-415c-93bd-01f4dc1ccd4f
2024-12-16 07:37:38    1342902 78c2ce52-f8c4-4d26-8fe0-4dc68faaa43e
2024-12-16 07:37:42  125401417 8a5d7789-42af-446a-a34f-eecd25577246
```
when I paste I get this
```
2024-12-16 06:58:48   74020152 ************************************
2024-12-16 07:00:20  204857981 ************************************
2024-12-16 07:02:14  201311016 ************************************
2024-12-16 07:37:38    1342902 ************************************
```

The Warp AI claimed I could get around this by holding Alt while selecting/copy text, but that does not work and the result is the same.
Apparently this is supposed to be a security thing (even though the UUIDs appear in the output and could easily be seen in a screenshot). Since this is a useless thing to do in the first place, please stop.

### To reproduce

1. run `uuidgen`
2. copy the output
3. try to paste it somewhere

### Expected behavior

I expect to be able to copy and paste UUIDs like any normal text.

### Operating system

Linux

### Operating system and version

Ubuntu 24.04.1

### Shell Version

GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.12.10.15.55.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by gdanov** [comment]
just experienced this today

**Comment by Advait-M** [comment]
Hey @swpalmer-cl @gdanov ! Thank you for raising this bug and sorry for the impact here!

I've confirmed this is a regression and I have a fix up for this internally. I'll update this thread when we have a release live with the fix soon - going to do a hotfix release.

**Comment by wolfe719** [comment]
Great! I just went through writing the same thing up... Looking forward to a hotfix!

**Comment by puelocesar** [comment]
Me too, this is really annoying. I have to open Settings -> Enable Secret redaction, disable Secret Redaction and now copy and paste works again 😠

**Comment by murtaza** [comment]
+1, would love a hotfix

**Comment by Advait-M** [comment]
Hey folks - this issue has been resolved and we've pushed a new release. Please update to `v0.2024.12.10.15.55.stable_04` which includes the fix for this.

Let us know if you have any other issues (please open a new issue)!

Sorry for the impact here!

**Comment by swpalmer-cl** [comment]
Appreciate the quick turn around on this. :clap:

**Comment by lessless** [comment]
> Hey folks - this issue has been resolved and we've pushed a new release. Please update to `v0.2024.12.10.15.55.stable_04` which includes the fix for this.
> 
> Let us know if you have any other issues (please open a new issue)!
> 
> Sorry for the impact here!

great! now I have to find something else on the Internet to be pissed off about 😕

**Comment by pshinoj** [comment]
I see the issue still happening when AI picks up the redacted secret to rerun the previous command
