### ISSUE TITLE
Theme is reset uppon closing/opening Warp

### ISSUE THREAD

**Issue by thrandale** [warpdotdev/Warp#5907]
### Pre-submit Checks

- [x] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates
- [x] I have [searched Warp known issues page](https://docs.warp.dev/help/known-issues) and my issue is not there

### Describe the bug

I set my theme in Warp to "Dracula". When I closed and re-opened Warp, the theme was reset to "Phenomenon". This behavior is the same regardless of what theme I select. It is always reset to "Phenomenon".

### To reproduce

1. Open Warp
2. Set the theme to "Dracula"
3. Close Warp
4. Open Warp and see that the theme has reset to "Phenomenon"

### Expected behavior

I would expect the theme to be remembered when I close and reopen Warp

### Screenshots

![Image](https://github.com/user-attachments/assets/cf15f29f-420c-46de-8dda-5418ada626c1)

### Operating system

Windows

### Operating system and version

Windows 11 23H2 Build 22631.4890

### Shell Version

PowerShell 7.5.0

### Current Warp version

v0.2025.02.24.20.50.stable_04

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

v0.2025.02.12.16.51

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by acarl005** [comment]
Hi @thrandale thanks for reporting the issue. Can you post your Warp log file at `$env:LOCALAPPDATA\warp\Warp\data\logs\warp.log`?

**Comment by thrandale** [comment]
Here you go [warp.log](https://github.com/user-attachments/files/18993175/warp.log)

This is from:
1. Open Warp
2. Set Dracula Theme
3. Close Warp

**Comment by thrandale** [comment]
I do not see a Settings sync option

![Image](https://github.com/user-attachments/assets/1e4d0669-558e-4992-b7a4-db9c3b10ca5f)

**Comment by danielpeng2** [comment]
We're looking into this, would you mind sending us the email that you used to sign into Warp so we can look into what's happening for your specific account? You can send it to me at daniel[at]warp[dot]dev.

**Comment by thrandale** [comment]
@danielpeng2 I have sent my email.

**Comment by danielpeng2** [comment]
If you're encountering this, try signing out and signing back in. We believe that should fix the issue.

**Comment by braider-andrey** [comment]
It is happening to me too

**Comment by danielpeng2** [comment]
@braider-andrey Have you tried signing out and signing back in?

**Comment by IGLADI** [comment]
Had the same bug, logging out and in fixes it.
This also affected other settings like the input position.

**Comment by shafnybuilds** [comment]
I've logged out and logged in, It doesn't fix mine 🥲, btw I'm a newbie to warp

**Comment by vinay9354** [comment]
i am facing same issue signing  out and login in back not working

**Comment by erlonbie** [comment]
Same issue on latest version.

**Comment by adampatterson** [comment]
This just started happening for me after setting up a new computer. I'm between them and each time I switch to a custom theme (Catppuccin) the other computer displays the default theme while the settings shows that it's using Catppuccin.

MY theory is that it has to do with my user path being changing between the two.

`adampatterson` vs `adam.patterson`

**Comment by acarl005** [comment]
@adampatterson Ah yes that is an issue. Custom themes are local to the device and the chosen theme is a name pointing to a theme and that _is_ shared between devices you are logged into but it fails to find local custom themes on the other devices. Something we need to fix.

**Comment by adampatterson** [comment]
Would it be possible to reference from the users root? '~'
