### ISSUE TITLE
Can't enter dot character (Windows)

### ISSUE THREAD

**Issue by funder7** [warpdotdev/Warp#6002]
### Pre-submit Checks

- [x] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates
- [x] I have [searched Warp known issues page](https://docs.warp.dev/help/known-issues) and my issue is not there
- [ ] I have included the logs (optional, but helps expedite the bug fix). [Log gathering intructions](https://docs.warp.dev/help/sending-us-feedback#gathering-warp-logs)

### Describe the bug

Hi,

There's an issue when writing dots into a WSL/Ubuntu shell (I'm using zsh).
I read that zsh is not completely supported yet, so I'm creating this issue only as a reminder for something to be fixed. 

As you can see in the screen recording, the `.` character is received as "n", blocking any command that relies on it. 

When copying commands into the terminal, the result doesn't change. 
Few minutes ago I copied a command in the terminal, all the dots have been replaced with the "n" char (even before pressing the enter key).

 

### To reproduce

1. Open a Linux shell on Windows
2. Type `.`
3. Press enter

### Expected behavior

The `.` character should be handled correctly

### Screenshots, videos, and logs

https://streamable.com/y2oph1

### Operating system

MacOS

### Operating system and version

Windows 11

### Shell Version

zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

### Current Warp version

v0.2025.02.24.20.50.stable_04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

- After opening the issue I created a new tab (same profile), and I was able to type correctly. The problem is intermittent.
- I encountered this issue in earlier versions.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment]
Hey @funder7! Thanks for filing!

We believe this bug repros when:
1) Using an italian keyboard layout
2) Using a WSL session with ZSH as the backing shell
3) Sourcing ohmyzsh in your ZSH rc profile.

Could you confirm those 3 things are true for you? We hope to have a fix for this soon, but in the meantime you can "unblock" yourself by either disabling ohmyzsh or by changing the shell to bash. 

It seems to be a bug in ohmyzsh's bracketed-paste implementation.

**Comment by ddbust81** [comment]
Hi All!
I am also experiencing this bug and I meet both of the mentioned conditions: Italian keyboard layout and use of WSL with ZSH and ohmyzsh.

**Comment by alokedesai** [comment]
Hi everyone, we have a fix for this (it's actually a bug in the implementation of [OpenConsole](https://learn.microsoft.com/en-us/windows/console/ecosystem-roadmap) we depend on, not in Warp).

We should have a fix out in the next two hours or so. Thanks for your patience here!

**Comment by alokedesai** [comment]
Hi @funder7. This should be fixed in the latest release. Could you try updating Warp and verifying it's fixed for you? Thanks!

**Comment by ddbust81** [comment]
Hello everyone,

I'm jumping into the discussion to suggest that, while waiting for a functional fix, the Warp terminal can be used with this workaround (you might have already done this):


```
❯ echo $TERM
xterm-256color
> echo "."
n echo "^[On"

> unset TERM
> echo "."
.
```
I know it's not ideal, since you lose some features, but at least you can use it while you wait.

**Comment by funder7** [comment]
Thanks @ddbust81!

I've tried today and it's workin 😃 
The version is `v0.2025.03.12.08.02.stable_03`!

**Comment by AleMScof** [comment]
I am still facing the mentioned bug on v0.2025.04.02.08.11.stable_03 

- Using an Italian keyboard layout | Yes
- Using a WSL session with ZSH as the backing shell | Yes
- Sourcing ohmyzsh in your ZSH rc profile | Yes

Do you have any suggestions on how to avoid this?

**Comment by alokedesai** [comment]
Hi everyone, this should now be fixed in the latest version of Warp. Please reopen if you're still seeing issues!
